### Login
POST http://192.168.0.1/goform/goform_set_cmd_process
Accept: application/json, text/javascript, */*; q=0.01
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

isTest=false&goformId=LOGIN_MULTI_USER&password=bTRjNXU1aDE%3D&user=admin

###
POST http://192.168.0.1/goform/goform_set_cmd_process
Accept: application/json, text/javascript, */*; q=0.01
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

isTest=false&goformId=REBOOT_DEVICE