ct_mysqlAddUserLinux() {
	local ID=$1
	sudo groupadd -g $ID mysql
	sudo useradd -u $ID mysql -M -g mysql
}



ct_mysqlAdmAddUserOnlyDataAccess() {
	local MY_USER=$1
	local MY_HOST=$2
	local MY_PASS=$3
	echo "CREATE USER '$MY_USER'@'$MY_HOST' IDENTIFIED VIA mysql_native_password USING '$MY_PASS';GRANT SELECT, INSERT, UPDATE, DELETE, FILE ON *.* TO 'adver523_afcombr'@'localhost' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;"
}

ct_mysqlAdmAddUserAllDataAccess() {
	local MY_USER=$1
	local MY_HOST=$2
	local MY_PASS=$3
	echo "CREATE USER '$MY_USER'@'$MY_HOST' IDENTIFIED VIA mysql_native_password USING '$MY_PASS';GRANT ALL PRIVILEGES ON *.* TO '$MY_USER'@'$MY_HOST' REQUIRE NONE WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;GRANT ALL PRIVILEGES ON `$MY_USER\_$MY_HOST`.* TO '$MY_USER'@'$MY_HOST';"
}